name: TheraBot CD

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    test:

        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v1

            - name: Set up Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Audit
              run: npm audit --production

            - name: Install packages
              run: npm install

            - name: Run tests
              run: npm test

            - name: Build
              run: npm run build

            - name: Deploy
              if: github.event_name == 'push'
              run: npx -q @ionaru/teamcity-deploy teamcity.saturnserver.org TheraBot_Build ${{ secrets.API_TOKEN }}
